logging:
  level:
    web: TRACE
    vtb:
      app: TRACE

application:
  session-data-service-url: http://localhost:8080/api/session
  virtdep:
    ws:
      uri: http://localhost:8080/ws
      stub:
        enabled: true
        port: 4545